package.json
src/Dashboard/Storage.ts
src/Dashboard/UploadTools.ts
src/utils/EditableTable.ts

Allow uploading word documents

---

src/utils/EditableTable.ts

Update Image Loading Features

---

.editorconfig
src/CressView.ts
src/Validation.ts
src/utils/EditableTable.ts

Init validator for cell-wise validation

---

deployment/scripts/editor.ts
src/CressView.ts
src/Dashboard/Storage.ts
src/Types.ts
src/utils/EditableTable.ts

- modify type `CressDoc` and `Doc`
- return both header and body in `Storage.ts`
- parse both header and body to `CressView`
- fuzzy name match for `image` column in `EditableTable` to fix image rendering
Refs: #39

Separate table header and body

---

assets/samples/SQUAREnotation-NEUMElevel.csv
deployment/scripts/editor.ts
package.json

Move samples/ to assets/

---

assets/css/style.css
src/utils/EditableTable.ts

Fix #21 ; Fix #24 ; Fix #33 ; Fix #34 ; Fix #48 ;

Fix table displaying and file exporting features

---

src/utils/EditableTable.ts

Support image resizing

---

src/utils/EditableTable.ts

fix: enable new image to be exported properly

---

package.json

Add workers folder when deploying

---

src/utils/EditableTable.ts

fix: convert quote signs to inch marks

---

assets/css/style.css
assets/template.html

fix: enable Home button in Editor

---

assets/css/style.css
assets/template.html

fix(UI): fix navbar styles in Editor to adjust small screens

---

src/Validation.ts

fix: update `meiStatus` font color for `processing`

---

.github/workflows/code-format.yml

Init workflow for code format check

---

.github/workflows/code-format.yml
assets/css/style.css
assets/template.html
deployment/scripts/editor.ts
deployment/server/dashboard.html
deployment/server/editor.html
deployment/server/index.html
package.json
src/Dashboard/Dashboard.ts
src/Dashboard/DashboardTools.ts
src/Dashboard/FileSystem/FileSystemTools.ts
src/Dashboard/Storage.ts
src/Dashboard/UploadArea.ts
src/Dashboard/UploadTools.ts
src/Editor/ColumnTools.ts
src/Editor/CressTable.ts
src/Editor/ExportHandler.ts
src/Editor/ImageHandler.ts
src/Validation.ts
src/utils/ModalWindow.ts
src/utils/Template.ts
yarn.lock

Add workflow for code format check 

---

assets/template.html
src/CressView.ts
src/Dashboard/Storage.ts
src/Editor/CressTable.ts

- Add `Save` to `File` nav bar drop-down
- Parse `id` to `CressTable`
- Add `updateAttachment()`
- Rename `initializeExportButtons()` to `initFileListener()`
- Add save file listener
Resolves: #26

Init save file to database

---

.eslintrc.js
.github/workflows/code-format.yml
.prettierignore
package.json
webpack.config.js
webpack.pages-config.js
yarn.lock

- Update webpack config files
- Update `code-format.yml`
- Reformat `.eslintrc.js`
- Ignore external files stored in `assets/js/`
Resolves: https://github.com/DDMAL/Cress/issues/81

Upgrade dependencies & update format check workflow

---

package.json
yarn.lock

fix: add `file-saver` package for excel exporting

---

src/Editor/CressTable.ts
src/Types.ts

- Introduce type `TableEvent`
- Add `initChangeListener`
Resolves: #50

Set to unsaved after edit actions other than cell editing

---

src/Dashboard/Storage.ts

fix: match image header when parsing excel file

---

assets/css/style.css

fix(UI): adjust navbar style in small screen

---

src/CressView.ts
src/Editor/CressTable.ts

fix: validate modified mei cells only

---

deployment/scripts/editor.ts
src/Editor/ImageTools.ts
src/Types.ts

fix: load sample csv file mei column

---

src/Dashboard/Storage.ts
src/Editor/MeiTools.ts
src/Types.ts

Introduce type `MeiData`

---

src/Editor/CressTable.ts
src/Editor/MeiTools.ts

Make validation status global

---

assets/img/empty-file.svg
deployment/server/dashboard.html
src/Dashboard/ContextMenuContent.ts
src/Dashboard/Dashboard.ts
src/Dashboard/DashboardContent.ts
src/utils/ModalWindow.ts

feat: support new empty file

---

src/Editor/MeiTools.ts

fix: remove `meiData` entry after clearing cell

---

src/Editor/CressTable.ts

- Make header search case insensitive
- Add notification if column not found
Resolves: #106

fix: error handling for extracting image and mei data
